### PR TITLE
Portico Plugin for OJS3

### PR DESCRIPTION
**Pull request by RahulChakravarthy**

### CODE REVIEW

**Comment by RahulChakravarthy** [comment]
@jmacgreg this should have the changes you requested, had to delete the previous branch it was giving issues

**Review by jmacgreg — CHANGES_REQUESTED** [review]
Hi Rahul, this looks 99% great! I've run a test and it appears to be working just fine. The only issue would be that there's still a locale/._en_US/ directory in there - can you remove that and resubmit the request?

**Comment by RahulChakravarthy** [comment]
Hi @jmacgreg, I made the changes, let me know if it worked

**Review by jmacgreg — APPROVED** [review]
Thanks Rahul, looks good!

**Pull request merged**
