### PR TITLE
Port recent improvements from master to stable-3_1_2

### PR DESCRIPTION
**Pull request by asmecher**
Some recent improvements have been merged to the `master` branch of the Portico plugin, but have not been ported to the `stable-3_1_2` branch. This PR resolves that.

### CODE REVIEW

**Comment by asmecher** [comment]
Heads-up @jonasraoni and @jmacgreg -- there are branches in this repo (`stable-3_1_1` and `stable-3_1_2`) corresponding to the OJS versions that the plugin is compatible with. I'm about to adapt `master` to be compatible with 3.2.x in preparation for a bit of further functionality to be added, and will then create a `stable-3_2_0` branch in order for `master` to become 3.3-compatible. Don't forget the other branches when merging in functionality (if it's easy to back-port)!

**Comment by jonasraoni** [comment]
@asmecher Yeah, I believe these updates might be moved to stable-3-1-2 without issues =]

I was going to introduce a XMLWriter and update other small things (e.g. add namespaces), but I think it will be more productive to turn the table... I've touched some import/export plugins and I think we don't need to depend so much on the internals 🤔
Next time I need to touch such plugin, I'll think about a more generic way to consume/produce data...

Right now I see two ways which are less likely to be impacted by internal changes:
- Consume the APIs: even though they can't be used to produce data yet... We also can leverage the Swagger file to generate [API clients in several languages](https://swagger.io/tools/swagger-codegen/) (perhaps we should publish such packages). 

- Interface with the `NativeImportExportPlugin` by producing XMLs or maybe interacting directly with it (if possible).

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by asmecher** [comment]
> I was going to introduce a XMLWriter...

Because the old `XMLCustomWriter` class was removed from pkp-lib between 3.2 and 3.3, I rewrote that part to use the PHP DOM toolset directly. Not quite what you were getting at but an improvement anyway.

**Comment by jonasraoni** [comment]
Yeah, while I was debugging I saw that it was returning a `DOMElement` instead of the `XMLNode`. I've added a reminder note to the optimization doc :)

**Pull request merged**
