### PR TITLE
Updated the plugin to work against the master branch of OJS

### PR DESCRIPTION
**Pull request by jonasraoni**
@jmacgreg, I've created this draft PR, so maybe it will be easier to point out some doubts =]

Some things that I remember:
- The current code is loading [galleys](https://github.com/jmacgreg/portico/blob/ojs3/PorticoExportPlugin.inc.php#L431) and [supplementary files](https://github.com/jmacgreg/portico/blob/ojs3/PorticoExportPlugin.inc.php#L459) from the same place, does it make sense? Were these concepts merged in OJS 3? If yes, great, I can refactor and use just one loop.

- This [loop will never run](https://github.com/jmacgreg/portico/blob/ojs3/PorticoExportDom.inc.php#L157) and [two lines below](https://github.com/jmacgreg/portico/blob/ojs3/PorticoExportDom.inc.php#L159), looks like the "xlink:href" should be pointing to a path instead of a name, etc. So my assumption that this branch was working fine in a previous OJS is false, right (which means that a more rigorous review is needed)?

- There are some checks for "isHTMLGalley" in the master branch, which I didn't see in this ojs3 branch. So, I guess it was removed from OJS, right?

- [This line will always fail](https://github.com/jmacgreg/portico/blob/ojs3/PorticoExportPlugin.inc.php#L233), so I replaced by "getLatestRevision" and almost in the same place this [condition seems to be wrong](https://github.com/jmacgreg/portico/blob/ojs3/PorticoExportPlugin.inc.php#L256), do you have any idea of what should be "rtSupplementaryFiles"? The only similar thing I found was a function named "convertSupplementaryFiles".

I removed [this](https://github.com/jmacgreg/portico/blob/ojs3/PorticoExportDom.inc.php#L213) and [this](https://github.com/jmacgreg/portico/blob/ojs3/PorticoExportDom.inc.php#L213) function since they are not being used, but it doesn't smell very well to me.

### CODE REVIEW

**Comment by jonasraoni** [comment]
Hi @jmacgreg, out of curiousity, is everything ok? :)

**Comment by jmacgreg** [comment]
Hi @jonasraoni - just getting back to this now! I have a client who can test this; we'll review and respond ASAP. Thank you!

**Comment by jmacgreg** [comment]
Hi @jonasraoni - we've tested, and it's working appropriately! Thank you! I'll merge and close this PR now.

**Comment by jonasraoni** [comment]
I was expecting something would break 😎

**Pull request merged**
