### PR TITLE
jmacgreg#10 Added support for remote galleys, extra author informatio…

### PR DESCRIPTION
**Pull request by jonasraoni**
…n (orcid ID, biography, country and moved the author email to the right place), removed warnings and improved the performance in general.

### CODE REVIEW

**Review by jmacgreg — APPROVED** [review]
Looks great Jonas, thanks! I'ved tested and it all checks out.

**Comment by asmecher** [comment]
@jonasraoni and @jmacgreg, the ORCID addition is causing problems; I have the following feedback:
> We recently had the journal (removed) try out the 3.2 version of the plugin to send us the files for Vol. x, No. y (from zzzz).  We received the files and they looked OK except that there was a new <contrib-id> element included. Our data ream reviewed the file and said that it isn’t a valid element for NLM 3.0 and so I wanted to reach out to see if you might make adjustments on your end to exclude it?

The `contrib-id` doesn't appear to be a valid part of Journal Archiving and Interchange Tag Set Tag Library version 3.0 (https://dtd.nlm.nih.gov/archiving/tag-library/3.0/index.html). Were you targeting a different version of JATS?

**Comment by jonasraoni** [comment]
Hi @asmecher! I've used the documentation sent from a PS client, so I can handle this issue.

So, a good addition here would be a DTD validation through a pre-commit/script/build, in general tests are always great, so I'll take a look here later: https://docs.pkp.sfu.ca/dev/testing/en/plugins-themes

**Comment by asmecher** [comment]
Sounds good, @jonasraoni -- I've filed that here: https://github.com/pkp/pkp-lib/issues/6603

**Pull request merged**
